#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: TRegExpr

# Short bio or description (displayed in the header)
description: Regular expressions in pure Delphi

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/1568089?v=3&u=f360ac3b8d7f85dd2a2e457ea4efaf1b2bb1a2f9&s=400

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: anso@mail.ru
  facebook:
  flickr:
  github: masterandrey/TRegExpr
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: andreyamoney
  stackoverflow: "users/4790975/masterandrey"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: masterandrey-com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-90467095-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http:/masterandrey.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

t:
  en:
    home:
      name: "Home"
      url: "/"
    syntax:
      name: "Syntax"
      url: "/regexp_syntax/"
    interface:
      name: "Interface"
      url: "/tregexpr_interface/"
    about:
      name: "About me"
      url: "/about/"
  ru:
    home:
      name: "Главная"
      url: "/index_ru.html"
    syntax:
      name: "Синтаксис"
      url: "/regexp_syntax_ru/"
    interface:
      name: "Интерфейс"
      url: "/tregexpr_interface_ru/"
    about:
      name: "Обо мне"
      url: "/about_ru/"

lang_names:
  en: "English"
  ru: "Русский"

search:
  en: "Search on the site..."
  ru: "Поиск по сайту..."


#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
